name: Ping Sitemap
on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/workflows/**.yml"
      - ".rusty-hook.toml"
      - "**/Makefile.toml"
      - "README.md"

jobs:
  ping-sitemap:
    runs-on: ubuntu-latest
    name: ping sitemap generator
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files in the docs folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v39
        with:
          json: true
          # write_output_files: true
          files: |
            articles/**
            esta_semena_en_rust/**

      - name: Run step if any file(s) in the src folder change
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          echo "One or more files in the src folder has changed."
          echo "${{ steps.changed-files-specific.outputs.all_modified_files }}"

      - name: Dispatch Modified Files
        #? @see https://github.com/peter-evans/repository-dispatch#example
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: ph4un00b/sitemap-rustico
          event-type: modified_pages
          client-payload: '{"from": "blog", "files": "${{ steps.changed-files-specific.outputs.all_changed_files }}", "other": "${{ steps.changed-files-specific.outputs.other_changed_files }}"}'
